"""Add category to problem

Revision ID: 3b251784fda5
Revises: 5a837880b70a
Create Date: 2020-09-12 19:00:20.193924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b251784fda5'
down_revision = '5a837880b70a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'category')
    # ### end Alembic commands ###
